/*
 * Références de son. Valeurs approximatives (réglages « de départ »), sur 10.
 * drive : clean | edge | crunch | overdrive | distortion | highgain | fuzz
 * gain : quantité de saturation visée (0 = très clair, 10 = saturation maximale)
 * pickup : neck | neck+middle | middle | middle+bridge | bridge | both
 * pickupType : single | humbucker | p90 | any
 * fx : comp, chorus, phaser, flanger, vibe, tremolo, wah, octave ('up'|'down'), delay { ms | note, mix, repeats }, reverb
 */
window.TONE_REFS = [
  // ---------------- Chansons ----------------
  { id: 'comfortably-numb', kind: 'song', title: 'Comfortably Numb (solo)', artist: 'Pink Floyd – David Gilmour',
    desc: 'Lead très soutenu et chantant : fuzz/distorsion douce sur un ampli clair et puissant, avec un long delay.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'single', guitarVol: 10, guitarTone: 8,
    drive: 'fuzz', gain: 7, eq: { bass: 5, mid: 6, treble: 6, presence: 5 },
    fx: { delay: { ms: 440, mix: 4, repeats: 4 }, reverb: 4 },
    tips: ['Grands bends lents et vibrato large.', 'Laisse sonner les notes : le delay fait la moitié du son.'] },
  { id: 'back-in-black', kind: 'song', title: 'Back in Black', artist: 'AC/DC – Angus Young',
    desc: 'Crunch rock sec et mordant, sans pédale : un ampli britannique poussé, beaucoup de médiums.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'crunch', gain: 5.5, eq: { bass: 5, mid: 7, treble: 6, presence: 6 }, fx: { reverb: 1 },
    tips: ['Moins de gain que ce qu’on croit : c’est l’attaque du médiator qui fait le son.', 'Accords courts et bien étouffés entre les coups.'] },
  { id: 'teen-spirit', kind: 'song', title: 'Smells Like Teen Spirit', artist: 'Nirvana – Kurt Cobain',
    desc: 'Couplets clairs avec chorus, refrains en distorsion épaisse.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'distortion', gain: 7.5, eq: { bass: 6, mid: 5, treble: 6, presence: 5 },
    fx: { chorus: { rate: 4, depth: 7, when: 'couplets (son clair)' }, reverb: 2 },
    tips: ['Couplet : son clair + chorus, juste 2 notes étouffées.', 'Refrain : distorsion à fond, power chords.'] },
  { id: 'under-the-bridge', kind: 'song', title: 'Under the Bridge', artist: 'Red Hot Chili Peppers – John Frusciante',
    desc: 'Clair, chaud et brillant, joué en accords enrichis sur le micro manche/milieu.',
    tuning: 'Standard', pickup: 'neck+middle', pickupType: 'single', guitarVol: 9, guitarTone: 8,
    drive: 'clean', gain: 1.5, eq: { bass: 5, mid: 5, treble: 6, presence: 5 }, fx: { comp: 3, reverb: 3 },
    tips: ['Attaque légère aux doigts ou au médiator souple.', 'Laisse résonner les cordes à vide.'] },
  { id: 'purple-haze', kind: 'song', title: 'Purple Haze', artist: 'Jimi Hendrix',
    desc: 'Fuzz rugueuse et octave aiguë sur ampli britannique poussé.',
    tuning: '½ ton plus bas (Mi♭)', pickup: 'bridge', pickupType: 'single', guitarVol: 10, guitarTone: 9,
    drive: 'fuzz', gain: 8, eq: { bass: 5, mid: 6, treble: 7, presence: 6 }, fx: { octave: 'up', reverb: 2 },
    tips: ['Baisse le volume de la guitare à 7 pour éclaircir la fuzz sur les rythmiques.'] },
  { id: 'little-wing', kind: 'song', title: 'Little Wing', artist: 'Jimi Hendrix',
    desc: 'Clair légèrement saturé avec un effet tournant (Leslie / Uni-Vibe).',
    tuning: '½ ton plus bas (Mi♭)', pickup: 'neck+middle', pickupType: 'single', guitarVol: 8, guitarTone: 8,
    drive: 'edge', gain: 3, eq: { bass: 5, mid: 6, treble: 6, presence: 5 }, fx: { vibe: { speed: 4, depth: 6 }, reverb: 3 },
    tips: ['Mélange accords et petites broderies (hammer-on / pull-off) dans l’accord.'] },
  { id: 'sultans', kind: 'song', title: 'Sultans of Swing', artist: 'Dire Straits – Mark Knopfler',
    desc: 'Clair « creux » et percussif, position 4 de la Strat, joué aux doigts.',
    tuning: 'Standard', pickup: 'neck+middle', pickupType: 'single', guitarVol: 10, guitarTone: 9,
    drive: 'clean', gain: 2, eq: { bass: 4, mid: 6, treble: 6, presence: 5 }, fx: { comp: 4, reverb: 2 },
    tips: ['Joue aux doigts (pouce + index + majeur), sans médiator : c’est 50 % du son.'] },
  { id: 'money-for-nothing', kind: 'song', title: 'Money for Nothing (riff)', artist: 'Dire Straits – Mark Knopfler',
    desc: 'Crunch épais avec une wah bloquée à mi-course : le son « nasillard ».',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'overdrive', gain: 6, eq: { bass: 5, mid: 7, treble: 5, presence: 5 }, fx: { wah: 'fixe à mi-course', reverb: 2 },
    tips: ['Trouve la position de wah où le son devient « nasal », puis ne bouge plus.'] },
  { id: 'streets', kind: 'song', title: 'Where the Streets Have No Name', artist: 'U2 – The Edge',
    desc: 'Clair brillant avec un delay en croche pointée qui crée un tapis de notes.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'single', guitarVol: 10, guitarTone: 10,
    drive: 'edge', gain: 3, eq: { bass: 4, mid: 5, treble: 7, presence: 6 },
    fx: { delay: { note: 'croche pointée', bpm: 126, mix: 6, repeats: 3 }, reverb: 3 },
    tips: ['Joue des croches régulières : le delay ajoute les notes entre.', 'Règle bien le temps du delay, sinon ça devient brouillon.'] },
  { id: 'master-of-puppets', kind: 'song', title: 'Master of Puppets', artist: 'Metallica – James Hetfield',
    desc: 'Haute saturation, médiums creusés, palm mute très serré.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'highgain', gain: 8.5, eq: { bass: 7, mid: 3, treble: 7, presence: 6 }, fx: { reverb: 1 },
    tips: ['Une overdrive (gain 0, niveau haut) devant l’ampli resserre les graves.', 'Palm mute : tranche de la main sur le chevalet.'] },
  { id: 'paranoid', kind: 'song', title: 'Paranoid / Iron Man', artist: 'Black Sabbath – Tony Iommi',
    desc: 'Saturation épaisse et sombre, très médium.',
    tuning: 'Standard (Iron Man) – souvent ½ ton plus bas', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 8,
    drive: 'distortion', gain: 7, eq: { bass: 6, mid: 7, treble: 5, presence: 5 }, fx: { reverb: 2 },
    tips: ['Riffs lourds et lents : laisse les notes respirer.'] },
  { id: 'whole-lotta-love', kind: 'song', title: 'Whole Lotta Love', artist: 'Led Zeppelin – Jimmy Page',
    desc: 'Crunch rond et grassouillet sur humbucker, saturation moyenne.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 9,
    drive: 'crunch', gain: 6, eq: { bass: 6, mid: 6, treble: 6, presence: 5 }, fx: { reverb: 3 },
    tips: ['Le riff se joue avec des glissés et des notes étouffées.'] },
  { id: 'sweet-child', kind: 'song', title: 'Sweet Child O’ Mine', artist: 'Guns N’ Roses – Slash',
    desc: 'Saturation chaude et chantante, beaucoup de médiums, micro manche pour l’intro.',
    tuning: '½ ton plus bas (Mi♭)', pickup: 'neck', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'distortion', gain: 7, eq: { bass: 5, mid: 7, treble: 6, presence: 5 }, fx: { delay: { ms: 380, mix: 2, repeats: 2 }, reverb: 3 },
    tips: ['Intro : laisse chaque note sonner (pas de palm mute).', 'Passe au micro chevalet pour les rythmiques.'] },
  { id: 'pride-and-joy', kind: 'song', title: 'Pride and Joy', artist: 'Stevie Ray Vaughan',
    desc: 'Clair « gras » très fort, poussé par une Tube Screamer peu saturée.',
    tuning: '½ ton plus bas (Mi♭)', pickup: 'neck', pickupType: 'single', guitarVol: 10, guitarTone: 9,
    drive: 'edge', gain: 4.5, eq: { bass: 6, mid: 6, treble: 6, presence: 5 }, fx: { reverb: 3 },
    tips: ['Attaque très forte du médiator, cordes épaisses si possible.', 'Shuffle : croches ternaires.'] },
  { id: 'thrill-is-gone', kind: 'song', title: 'The Thrill Is Gone', artist: 'B.B. King',
    desc: 'Clair chaud et doux, très peu de saturation, vibrato expressif.',
    tuning: 'Standard', pickup: 'neck+middle', pickupType: 'humbucker', guitarVol: 9, guitarTone: 7,
    drive: 'clean', gain: 2, eq: { bass: 5, mid: 6, treble: 5, presence: 4 }, fx: { comp: 3, reverb: 3 },
    tips: ['Peu de notes, beaucoup de vibrato (secoue le doigt sur la corde).'] },
  { id: 'sunshine', kind: 'song', title: 'Sunshine of Your Love', artist: 'Cream – Eric Clapton',
    desc: 'Le « woman tone » : saturation épaisse sur micro manche, tonalité guitare presque fermée.',
    tuning: 'Standard', pickup: 'neck', pickupType: 'humbucker', guitarVol: 10, guitarTone: 1,
    drive: 'distortion', gain: 7, eq: { bass: 5, mid: 7, treble: 7, presence: 6 }, fx: { reverb: 2 },
    tips: ['Ferme presque complètement le bouton de tonalité de la guitare : c’est tout le secret.'] },
  { id: 'gravity', kind: 'song', title: 'Gravity', artist: 'John Mayer',
    desc: 'Clair au bord de la saturation, chaud, avec une overdrive douce.',
    tuning: 'Standard', pickup: 'neck', pickupType: 'single', guitarVol: 9, guitarTone: 8,
    drive: 'edge', gain: 3.5, eq: { bass: 5, mid: 6, treble: 5, presence: 5 }, fx: { reverb: 4 },
    tips: ['Joue doucement : le son doit devenir plus « gras » quand tu attaques fort.'] },
  { id: 'get-lucky', kind: 'song', title: 'Get Lucky / Le Freak', artist: 'Nile Rodgers',
    desc: 'Funk très clair, brillant et compressé, rythmique en doubles croches.',
    tuning: 'Standard', pickup: 'middle+bridge', pickupType: 'single', guitarVol: 10, guitarTone: 10,
    drive: 'clean', gain: 1, eq: { bass: 3, mid: 5, treble: 7, presence: 6 }, fx: { comp: 6, reverb: 1 },
    tips: ['La main droite ne s’arrête jamais ; la main gauche fait les silences.', 'Accords de 3 notes sur les cordes aiguës.'] },
  { id: 'last-nite', kind: 'song', title: 'Last Nite', artist: 'The Strokes',
    desc: 'Crunch léger, médium et un peu « lo-fi », sans effets.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'single', guitarVol: 10, guitarTone: 8,
    drive: 'crunch', gain: 4.5, eq: { bass: 4, mid: 7, treble: 5, presence: 4 }, fx: {},
    tips: ['Pas de reverb : son sec et direct.', 'Ampli pas trop fort, le grain vient de l’ampli « juste poussé ».'] },
  { id: 'plug-in-baby', kind: 'song', title: 'Plug In Baby', artist: 'Muse – Matt Bellamy',
    desc: 'Fuzz très agressive et compressée.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'fuzz', gain: 9, eq: { bass: 6, mid: 6, treble: 7, presence: 6 }, fx: { delay: { ms: 300, mix: 2, repeats: 2 }, reverb: 2 },
    tips: ['Le riff en arpège doit être très net : coupe les cordes qui ne jouent pas.'] },
  { id: 'creep', kind: 'song', title: 'Creep', artist: 'Radiohead',
    desc: 'Couplets clairs et doux, puis les fameux « coups » de distorsion très agressive.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'any', guitarVol: 10, guitarTone: 10,
    drive: 'distortion', gain: 8, eq: { bass: 6, mid: 6, treble: 7, presence: 6 }, fx: { reverb: 3 },
    tips: ['Couplets : micro manche, son clair, arpèges.', 'Les coups de distorsion juste avant le refrain : deux coups de médiator très forts.'] },
  { id: 'basket-case', kind: 'song', title: 'Basket Case', artist: 'Green Day',
    desc: 'Saturation punk compacte, beaucoup de médiums, power chords.',
    tuning: '½ ton plus bas (Mi♭)', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'distortion', gain: 7, eq: { bass: 6, mid: 7, treble: 6, presence: 5 }, fx: { reverb: 1 },
    tips: ['Palm mute sur les couplets, ouvert sur les refrains.', 'Tout vers le bas, en croches.'] },
  { id: 'eruption', kind: 'song', title: 'Eruption / Ain’t Talkin’ ’Bout Love', artist: 'Van Halen',
    desc: 'Le « brown sound » : saturation chaude d’ampli poussé, un peu de phaser.',
    tuning: '½ ton plus bas (Mi♭)', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'highgain', gain: 7.5, eq: { bass: 5, mid: 7, treble: 6, presence: 6 }, fx: { phaser: { speed: 3, depth: 5 }, delay: { ms: 300, mix: 2, repeats: 1 }, reverb: 4 },
    tips: ['Tapping à deux mains sur Eruption.'] },
  { id: 'seven-nation', kind: 'song', title: 'Seven Nation Army', artist: 'The White Stripes – Jack White',
    desc: 'Riff à l’octave inférieure (effet « basse ») avec une fuzz.',
    tuning: 'Standard', pickup: 'neck', pickupType: 'any', guitarVol: 10, guitarTone: 8,
    drive: 'fuzz', gain: 7, eq: { bass: 7, mid: 6, treble: 5, presence: 5 }, fx: { octave: 'down', reverb: 2 },
    tips: ['Sans octaver, joue le riff sur les cordes graves : c’est déjà bien proche.'] },
  { id: 'killing-in-the-name', kind: 'song', title: 'Killing in the Name', artist: 'Rage Against the Machine – Tom Morello',
    desc: 'Haute saturation sèche et médium, en drop D.',
    tuning: 'Drop D (Ré grave)', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'highgain', gain: 7.5, eq: { bass: 6, mid: 6, treble: 6, presence: 6 }, fx: { wah: 'pour les effets / solos' },
    tips: ['Son assez sec, pas de reverb.'] },
  { id: 'still-got-the-blues', kind: 'song', title: 'Still Got the Blues', artist: 'Gary Moore',
    desc: 'Lead soutenu et chantant sur micro manche, saturation moyenne-forte.',
    tuning: 'Standard', pickup: 'neck', pickupType: 'humbucker', guitarVol: 10, guitarTone: 8,
    drive: 'overdrive', gain: 7, eq: { bass: 5, mid: 7, treble: 6, presence: 5 }, fx: { delay: { ms: 400, mix: 3, repeats: 3 }, reverb: 4 },
    tips: ['Beaucoup de vibrato, notes tenues longtemps.'] },
  { id: 'europa', kind: 'song', title: 'Europa', artist: 'Santana',
    desc: 'Lead très soutenu, chaud et doux, quasi infini.',
    tuning: 'Standard', pickup: 'neck', pickupType: 'humbucker', guitarVol: 10, guitarTone: 7,
    drive: 'overdrive', gain: 7.5, eq: { bass: 5, mid: 8, treble: 5, presence: 4 }, fx: { delay: { ms: 450, mix: 3, repeats: 3 }, reverb: 5 },
    tips: ['Joue fort et proche de l’ampli pour que les notes tiennent (larsen contrôlé).'] },

  // ---------------- Artistes ----------------
  { id: 'brian-may', kind: 'artist', title: 'Brian May (Queen)', artist: 'Queen',
    desc: 'Saturation douce et très chantante, avec un treble booster dans un ampli Vox.',
    tuning: 'Standard', pickup: 'middle+bridge', pickupType: 'single', guitarVol: 10, guitarTone: 10,
    drive: 'overdrive', gain: 6.5, eq: { bass: 4, mid: 7, treble: 7, presence: 6 }, fx: { delay: { ms: 800, mix: 3, repeats: 2 }, reverb: 3 },
    tips: ['Il joue avec une pièce de monnaie en guise de médiator.'] },
  { id: 'frusciante-funk', kind: 'artist', title: 'Frusciante (rythmiques funk)', artist: 'Red Hot Chili Peppers',
    desc: 'Clair sec et percussif, légèrement compressé.',
    tuning: 'Standard', pickup: 'neck+middle', pickupType: 'single', guitarVol: 10, guitarTone: 9,
    drive: 'clean', gain: 2, eq: { bass: 4, mid: 6, treble: 6, presence: 5 }, fx: { comp: 4 },
    tips: ['Coups étouffés très présents entre les accords.'] },
  { id: 'gilmour', kind: 'artist', title: 'David Gilmour (son général)', artist: 'Pink Floyd',
    desc: 'Clair profond ou saturation soutenue, toujours avec delay et un peu de modulation.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'single', guitarVol: 10, guitarTone: 9,
    drive: 'overdrive', gain: 6, eq: { bass: 5, mid: 6, treble: 6, presence: 5 }, fx: { comp: 3, chorus: { rate: 3, depth: 3 }, delay: { ms: 480, mix: 4, repeats: 4 }, reverb: 4 },
    tips: ['Phrases lentes, bends très justes.'] },
  { id: 'hendrix', kind: 'artist', title: 'Jimi Hendrix (son général)', artist: 'Jimi Hendrix',
    desc: 'Strat dans un Marshall poussé, fuzz pour les solos, Uni-Vibe et wah.',
    tuning: '½ ton plus bas (Mi♭)', pickup: 'neck', pickupType: 'single', guitarVol: 10, guitarTone: 9,
    drive: 'crunch', gain: 6, eq: { bass: 5, mid: 6, treble: 6, presence: 6 }, fx: { vibe: { speed: 4, depth: 5 }, wah: 'pour les solos', reverb: 2 },
    tips: ['Utilise le volume de la guitare : 6-7 pour la rythmique, 10 pour les solos.'] },
  { id: 'srv', kind: 'artist', title: 'Stevie Ray Vaughan / blues texan', artist: 'SRV',
    desc: 'Clair très fort et dynamique, poussé par une Tube Screamer.',
    tuning: '½ ton plus bas (Mi♭)', pickup: 'neck', pickupType: 'single', guitarVol: 10, guitarTone: 9,
    drive: 'edge', gain: 5, eq: { bass: 6, mid: 6, treble: 6, presence: 5 }, fx: { reverb: 3, vibe: { speed: 5, depth: 4, when: 'certains morceaux' } },
    tips: ['Attaque forte, cordes épaisses.'] },
  { id: 'the-edge', kind: 'artist', title: 'The Edge (U2)', artist: 'U2',
    desc: 'Clair brillant, delays rythmiques en croche pointée, ambiances.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'single', guitarVol: 10, guitarTone: 10,
    drive: 'edge', gain: 3, eq: { bass: 4, mid: 5, treble: 7, presence: 6 }, fx: { delay: { note: 'croche pointée', bpm: 120, mix: 6, repeats: 3 }, chorus: { rate: 3, depth: 3 }, reverb: 4 },
    tips: ['Peu de notes, beaucoup de répétitions.'] },
  { id: 'nile', kind: 'artist', title: 'Nile Rodgers / funk disco', artist: 'Chic',
    desc: 'Clair, brillant, compressé.', tuning: 'Standard', pickup: 'middle+bridge', pickupType: 'single', guitarVol: 10, guitarTone: 10,
    drive: 'clean', gain: 1, eq: { bass: 3, mid: 5, treble: 7, presence: 6 }, fx: { comp: 6, reverb: 1 }, tips: ['Doubles croches non-stop.'] },
  { id: 'tame-impala', kind: 'artist', title: 'Tame Impala / psyché moderne', artist: 'Kevin Parker',
    desc: 'Fuzz arrondie, phaser et chorus, beaucoup d’espace.',
    tuning: 'Standard', pickup: 'neck', pickupType: 'any', guitarVol: 10, guitarTone: 7,
    drive: 'fuzz', gain: 6, eq: { bass: 5, mid: 5, treble: 5, presence: 4 }, fx: { phaser: { speed: 3, depth: 6 }, chorus: { rate: 2, depth: 5 }, delay: { ms: 350, mix: 3, repeats: 3 }, reverb: 5 },
    tips: ['Ton de guitare un peu fermé pour arrondir la fuzz.'] },

  // ---------------- Styles ----------------
  { id: 'st-clean-pop', kind: 'style', title: 'Clair pop', desc: 'Clair net et équilibré, un peu de reverb.',
    tuning: 'Standard', pickup: 'neck+middle', pickupType: 'any', guitarVol: 10, guitarTone: 8,
    drive: 'clean', gain: 1.5, eq: { bass: 5, mid: 5, treble: 6, presence: 5 }, fx: { comp: 2, chorus: { rate: 3, depth: 3, optional: true }, reverb: 4 }, tips: [] },
  { id: 'st-funk', kind: 'style', title: 'Funk', desc: 'Clair brillant, compressé, percussif.',
    tuning: 'Standard', pickup: 'middle+bridge', pickupType: 'single', guitarVol: 10, guitarTone: 10,
    drive: 'clean', gain: 1, eq: { bass: 3, mid: 5, treble: 7, presence: 6 }, fx: { comp: 6, wah: 'optionnelle, pour les rythmiques', reverb: 1 }, tips: ['Main droite toujours en mouvement.'] },
  { id: 'st-blues', kind: 'style', title: 'Blues crunch', desc: 'Clair qui sature quand on attaque fort.',
    tuning: 'Standard', pickup: 'neck', pickupType: 'any', guitarVol: 10, guitarTone: 8,
    drive: 'edge', gain: 4.5, eq: { bass: 5, mid: 6, treble: 6, presence: 5 }, fx: { reverb: 3 }, tips: ['Joue avec le volume de la guitare.'] },
  { id: 'st-classic-rock', kind: 'style', title: 'Rock classique (années 70)', desc: 'Crunch médium, ampli britannique poussé.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'crunch', gain: 6, eq: { bass: 5, mid: 7, treble: 6, presence: 6 }, fx: { reverb: 2 }, tips: [] },
  { id: 'st-hard-80', kind: 'style', title: 'Hard rock années 80', desc: 'Saturation épaisse, solos avec delay.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'highgain', gain: 7.5, eq: { bass: 6, mid: 6, treble: 7, presence: 6 }, fx: { chorus: { rate: 3, depth: 3, optional: true }, delay: { ms: 400, mix: 3, repeats: 3 }, reverb: 3 }, tips: [] },
  { id: 'st-grunge', kind: 'style', title: 'Grunge', desc: 'Distorsion épaisse et sale, médiums un peu creusés.',
    tuning: 'Standard ou Drop D', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'distortion', gain: 8, eq: { bass: 6, mid: 4, treble: 6, presence: 5 }, fx: { chorus: { rate: 4, depth: 6, when: 'parties claires' }, reverb: 2 }, tips: [] },
  { id: 'st-punk', kind: 'style', title: 'Punk rock', desc: 'Saturation compacte et médium, très peu d’effets.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'distortion', gain: 7, eq: { bass: 6, mid: 7, treble: 6, presence: 5 }, fx: {}, tips: ['Tout en coups vers le bas.'] },
  { id: 'st-metal', kind: 'style', title: 'Metal', desc: 'Haute saturation serrée, médiums creusés.',
    tuning: 'Standard, Drop D ou plus bas', pickup: 'bridge', pickupType: 'humbucker', guitarVol: 10, guitarTone: 10,
    drive: 'highgain', gain: 8.5, eq: { bass: 7, mid: 3.5, treble: 7, presence: 7 }, fx: { reverb: 1 }, tips: ['Overdrive en boost (gain 0, niveau haut) devant l’ampli pour resserrer.'] },
  { id: 'st-indie', kind: 'style', title: 'Indie / garage', desc: 'Crunch léger, médium, souvent sec.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'any', guitarVol: 10, guitarTone: 9,
    drive: 'crunch', gain: 5, eq: { bass: 4, mid: 7, treble: 6, presence: 5 }, fx: { reverb: 1 }, tips: [] },
  { id: 'st-ambient', kind: 'style', title: 'Ambient / post-rock', desc: 'Clair, beaucoup de delay et de reverb.',
    tuning: 'Standard', pickup: 'neck', pickupType: 'any', guitarVol: 8, guitarTone: 7,
    drive: 'clean', gain: 2, eq: { bass: 5, mid: 5, treble: 5, presence: 4 }, fx: { delay: { ms: 550, mix: 5, repeats: 6 }, reverb: 8, tremolo: { speed: 4, depth: 3, optional: true } }, tips: ['Monte doucement le volume de la guitare pour des attaques invisibles.'] },
  { id: 'st-country', kind: 'style', title: 'Country (twang)', desc: 'Clair claquant, compressé, avec un écho court (slapback).',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'single', guitarVol: 10, guitarTone: 10,
    drive: 'clean', gain: 1.5, eq: { bass: 4, mid: 5, treble: 7, presence: 6 }, fx: { comp: 5, delay: { ms: 110, mix: 4, repeats: 1 }, reverb: 2 }, tips: ['Hybrid picking : médiator + doigts.'] },
  { id: 'st-jazz', kind: 'style', title: 'Jazz', desc: 'Clair rond et chaud, aigus coupés.',
    tuning: 'Standard', pickup: 'neck', pickupType: 'humbucker', guitarVol: 9, guitarTone: 4,
    drive: 'clean', gain: 1, eq: { bass: 6, mid: 5, treble: 3, presence: 3 }, fx: { reverb: 2 }, tips: ['Cordes plus épaisses si possible.'] },
  { id: 'st-reggae', kind: 'style', title: 'Reggae (skank)', desc: 'Clair sec et brillant, graves coupés.',
    tuning: 'Standard', pickup: 'middle+bridge', pickupType: 'any', guitarVol: 10, guitarTone: 10,
    drive: 'clean', gain: 1, eq: { bass: 2, mid: 5, treble: 7, presence: 6 }, fx: { reverb: 2 }, tips: ['Étouffe l’accord juste après chaque coup.'] },
  { id: 'st-shoegaze', kind: 'style', title: 'Shoegaze', desc: 'Mur de fuzz noyé de reverb, modulation.',
    tuning: 'Standard', pickup: 'bridge', pickupType: 'any', guitarVol: 10, guitarTone: 7,
    drive: 'fuzz', gain: 8, eq: { bass: 6, mid: 5, treble: 5, presence: 4 }, fx: { chorus: { rate: 2, depth: 6 }, delay: { ms: 450, mix: 4, repeats: 5 }, reverb: 9 }, tips: ['Joue en bougeant légèrement le vibrato.'] }
];
